
#container => service

services:
  mysql-springboot-container:
    image: mysql:8.0.36-debian
    container_name: mysql-springboot-container
    ports:
      - 3310:3306
    volumes:
      - mysql-springboot-data:/var/lib/mysql
      - mysql-springboot-config-deamond:/etc/mysql/conf.d
    networks:
      - backend
    environment:
      MYSQL_USER: hieulc
      MYSQL_PASSWORD: hieulc
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: StudentManagement

  springboot-docker-container:
    image: hieule01/springboot-docker:v1.0.0
    ports:
      - 8085:8080
    volumes:
      - ./:/app
    networks:
      - backend

#create network
networks:
  backend:
    name: springboot-app-network
volumes:
  mysql-springboot-data:
  mysql-springboot-config-deamond:





